version: '2'
services:
  nginxproxy:
    image: nginx
    container_name: nginxproxy
    ports:
      - "5000:80"
    volumes:
      - /etc/nginx/conf.d
  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup nginxproxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginxproxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
  webapp:
    restart: always
    build: 
      context: .
      dockerfile: webapp.dockerfile
    environment:
      - "SERVER_URL=http://*:80"
      - VIRTUAL_HOST=localhost